version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    volumes:
      - ./api:/app
      - /app/node_modules

  ui:
    build: ./ui
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: npm start
    volumes:
      - ./ui:/app
      - /app/node_modules
